### ISSUE TITLE
Set GitHub project defaults

### ISSUE THREAD

**Issue by MattKotsenas** [rjmurillo/moq.analyzers#19]
- [x] Squash by default (appears to currently be set to merge)
- [x] Set the squashed commit message to the PR message

**Comment by rjmurillo** [comment]
@Litee I don't have access to settings to make these and other changes for the pipelines. Can you make them or transfer ownership to me so I can make them?

**Comment by Litee** [comment]
Sorry, have no time to do it right now. Will take a look on Friday or over the weekend.

**Comment by Litee** [comment]
@rjmurillo , I tried to pass ownership, but got "rjmurillo/moq.analyzers already exists" error.

**Comment by rjmurillo** [comment]
@Litee I've removed my fork. Please try to transfer ownership again

**Comment by Litee** [comment]
Transfer initiated for both moq.* repos.

**Comment by rjmurillo** [comment]
@Litee Thank you, the transfer was successful

**Comment by rjmurillo** [comment]
Settings updated
