### ISSUE TITLE
How to suppress? Doc doesn't say

### ISSUE THREAD

**Issue by abatishchev** [rjmurillo/moq.analyzers#238]
Currently neither https://github.com/rjmurillo/moq.analyzers/blob/main/README.md nor https://github.com/rjmurillo/moq.analyzers/blob/main/docs/rules/README.md explain how to suppress a rule.

**Comment by MattKotsenas** [comment]
Hi there! Thanks for your interest!

Moq.Analyzers can be configured via any of the existing analyzer configuration methods (.editorconfig, inline suppressions, etc.). Documentation is available here: https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/suppress-warnings.

I'll make a PR now to add this to the README.
